a = {'worker': {'gpu_capacity': {'nvidia_gpu_amd64': 1}, 'name': 'worker', 'unschedulable': False,
                'labels': {'all': 'active', 'webui2': 'active', 'cloud-fluentd-es-v2.0.2': 'active',
                           'beta.kubernetes.io/os': 'linux', 'kubernetes.io/arch': 'amd64',
                           'custom-user-dashboard-backend-arm64': 'active', 'glusterfs': 'active',
                           'beta.kubernetes.io/arch': 'amd64', 'hdfs': 'active',
                           'custom-user-dashboard-backend': 'active', 'nvidia-device-plugin-daemonset': 'active',
                           'custom-user-dashboard-frontend-arm64': 'active', 'cloud-fluentd-es-config-v0.1.0': 'active',
                           'fluent-bit': 'active', 'datanode': 'active', 'gpu': 'active',
                           'grafana-configuration': 'active', 'a910-device-plugin': 'active',
                           'prometheus-alert': 'active', 'archType': 'amd64', 'kubernetes.io/hostname': 'worker',
                           'worker': 'active', 'fluent-bit-config': 'active', 'nginx': 'active',
                           'alert-templates': 'active', 'kubernetes.io/os': 'linux', 'job-exporter': 'active',
                           'custom-user-dashboard-frontend': 'active', 'blobfuse-flexvol-installer': 'active',
                           'dotnet-server': 'active', 'FragmentGPUJob': 'active', 'freeflowrouter': 'active',
                           'default': 'active', 'dlws-scripts': 'active', 'google-cadvisor': 'active',
                           'dashboard': 'active', 'openresty': 'active', 'nvidia': 'active', 'node-exporter': 'active',
                           'gpuType': 'nvidia_gpu_amd64'}, 'gpu_allocatable': {'nvidia_gpu_amd64': 1},
                'InternalIP': '10.31.3.109',
                'scheduled_service': ['webui2', 'cloud-fluentd-es-v2.0.2', 'custom-user-dashboard-backend-arm64',
                                      'glusterfs', 'hdfs', 'custom-user-dashboard-backend',
                                      'nvidia-device-plugin-daemonset', 'custom-user-dashboard-frontend-arm64',
                                      'cloud-fluentd-es-config-v0.1.0', 'fluent-bit', 'datanode', 'gpu',
                                      'grafana-configuration', 'a910-device-plugin', 'prometheus-alert', 'worker',
                                      'fluent-bit-config', 'nginx', 'alert-templates', 'job-exporter',
                                      'custom-user-dashboard-frontend', 'blobfuse-flexvol-installer', 'dotnet-server',
                                      'FragmentGPUJob', 'freeflowrouter', 'dlws-scripts', 'google-cadvisor',
                                      'dashboard', 'openresty', 'nvidia', 'node-exporter', 'nvidia_gpu_amd64'],
                'gpu_preemptable_used': {'nvidia_gpu_amd64': 0},
                'pods': ['nginx-8758z (cpu #:0)', 'prometheus-operator-79cf7bc9f-f5l6p (cpu #:0)'],
                'gpuType': 'nvidia_gpu_amd64', 'gpu_used': {'nvidia_gpu_amd64': 0}},
     'atlas01': {'gpu_capacity': {'huawei_npu_arm64': 8}, 'name': 'atlas01', 'unschedulable': False,
                 'labels': {'all': 'active', 'webui2': 'active', 'cloud-fluentd-es-v2.0.2': 'active',
                            'dldocs': 'active', 'custom-user-dashboard-backend-arm64': 'active', 'glusterfs': 'active',
                            'hdfs': 'active', 'custom-user-dashboard-backend': 'active',
                            'nvidia-device-plugin-daemonset': 'active',
                            'custom-user-dashboard-frontend-arm64': 'active',
                            'cloud-fluentd-es-config-v0.1.0': 'active', 'huawei': 'active', 'fluent-bit': 'active',
                            'datanode': 'active', 'grafana-configuration': 'active', 'a910-device-plugin': 'active',
                            'prometheus-alert': 'active', 'archType': 'arm64', 'kubernetes.io/hostname': 'atlas01',
                            'worker': 'active', 'fluent-bit-config': 'active', 'nginx': 'active',
                            'alert-templates': 'active', 'kubernetes.io/arch': 'arm64', 'npu': 'active',
                            'job-exporter': 'active', 'custom-user-dashboard-frontend': 'active',
                            'blobfuse-flexvol-installer': 'active', 'dotnet-server': 'active',
                            'FragmentGPUJob': 'active', 'freeflowrouter': 'active', 'default': 'active',
                            'kubernetes.io/os': 'linux', 'dlws-scripts': 'active', 'google-cadvisor': 'active',
                            'dashboard': 'active', 'openresty': 'active', 'node-exporter': 'active',
                            'gpuType': 'huawei_npu_arm64'}, 'gpu_allocatable': {'huawei_npu_arm64': 8},
                 'InternalIP': '10.31.3.247', 'scheduled_service': ['webui2', 'cloud-fluentd-es-v2.0.2', 'dldocs',
                                                                    'custom-user-dashboard-backend-arm64', 'glusterfs',
                                                                    'hdfs', 'custom-user-dashboard-backend',
                                                                    'nvidia-device-plugin-daemonset',
                                                                    'custom-user-dashboard-frontend-arm64',
                                                                    'cloud-fluentd-es-config-v0.1.0', 'huawei',
                                                                    'fluent-bit', 'datanode', 'grafana-configuration',
                                                                    'a910-device-plugin', 'prometheus-alert', 'worker',
                                                                    'fluent-bit-config', 'nginx', 'alert-templates',
                                                                    'npu', 'job-exporter',
                                                                    'custom-user-dashboard-frontend',
                                                                    'blobfuse-flexvol-installer', 'dotnet-server',
                                                                    'FragmentGPUJob', 'freeflowrouter', 'dlws-scripts',
                                                                    'google-cadvisor', 'dashboard', 'openresty',
                                                                    'node-exporter', 'huawei_npu_arm64'],
                 'gpu_preemptable_used': {}, 'pods': [], 'gpuType': 'huawei_npu_arm64', 'gpu_used': {}},
     'master': {'gpu_capacity': {}, 'name': 'master', 'unschedulable': False,
                'labels': {'all': 'active', 'webui2': 'active', 'cloud-fluentd-es-v2.0.2': 'active',
                           'beta.kubernetes.io/os': 'linux', 'jobmanager2': 'active', 'kibana': 'active',
                           'custom-user-dashboard-backend-arm64': 'active', 'mysql': 'active', 'watchdog': 'active',
                           'beta.kubernetes.io/arch': 'amd64', 'webui3': 'active', 'prometheus-alert': 'active',
                           'user-synchronizer': 'active', 'blobfuse-flexvol-installer': 'active',
                           'custom-user-dashboard-backend': 'active', 'nvidia-device-plugin-daemonset': 'active',
                           'custom-user-dashboard-frontend-arm64': 'active', 'cloud-fluentd-es-config-v0.1.0': 'active',
                           'grafana': 'active', 'archType': 'amd64', 'fluent-bit': 'active', 'datanode': 'active',
                           'google-cadvisor': 'active', 'dotnet-server': 'active', 'dashboard': 'active',
                           'grafana-configuration': 'active', 'restfulapi2': 'active', 'infrastructure': 'active',
                           'journalnode': 'active', 'node-role.kubernetes.io/master': '', 'namenode1': 'active',
                           'kubernetes.io/hostname': 'master', 'fluent-bit-config': 'active', 'nginx': 'active',
                           'prometheus': 'active', 'alert-templates': 'active', 'kubernetes.io/arch': 'amd64',
                           'job-exporter': 'active', 'custom-user-dashboard-frontend': 'active', 'webportal': 'active',
                           'restfulapi': 'active', 'FragmentGPUJob': 'active', 'freeflowrouter': 'active',
                           'default': 'active', 'jobmanager': 'active', 'kubernetes.io/os': 'linux',
                           'zookeeper': 'active', 'alert-manager': 'active', 'openresty': 'active',
                           'repairmanager': 'active', 'node-exporter': 'active', 'dlws-scripts': 'active'},
                'gpu_allocatable': {}, 'InternalIP': '10.31.3.108',
                'scheduled_service': ['webui2', 'cloud-fluentd-es-v2.0.2', 'jobmanager2', 'kibana',
                                      'custom-user-dashboard-backend-arm64', 'mysql', 'watchdog', 'webui3',
                                      'prometheus-alert', 'user-synchronizer', 'blobfuse-flexvol-installer',
                                      'custom-user-dashboard-backend', 'nvidia-device-plugin-daemonset',
                                      'custom-user-dashboard-frontend-arm64', 'cloud-fluentd-es-config-v0.1.0',
                                      'grafana', 'fluent-bit', 'datanode', 'google-cadvisor', 'dotnet-server',
                                      'dashboard', 'grafana-configuration', 'restfulapi2', 'infrastructure',
                                      'journalnode', 'namenode1', 'fluent-bit-config', 'nginx', 'prometheus',
                                      'alert-templates', 'job-exporter', 'custom-user-dashboard-frontend', 'webportal',
                                      'restfulapi', 'FragmentGPUJob', 'freeflowrouter', 'jobmanager', 'zookeeper',
                                      'alert-manager', 'openresty', 'repairmanager', 'node-exporter', 'dlws-scripts'],
                'gpu_preemptable_used': {'': 0}, 'pods': ['custom-user-dashboard-backend-g6vrj (cpu #:0) (cpu #:0)',
                                                          'custom-user-dashboard-frontend-rbjr9 (cpu #:0)',
                                                          'dldocs-wzmv4 (cpu #:0)',
                                                          'jobmanager-np2df (cpu #:0) (cpu #:0)',
                                                          'nginx-nz8xl (cpu #:0)', 'openresty-ql4m4 (cpu #:0)',
                                                          'restfulapi-s9ql7 (cpu #:0)', 'webui3-kjf98 (cpu #:0)'],
                'gpuType': '', 'gpu_used': {'': 0}}}
b = {'gpu_capacity': {'huawei_npu_arm64': 8}, 'name': 'atlas01', 'unschedulable': False,
     'labels': {'all': 'active', 'webui2': 'active', 'cloud-fluentd-es-v2.0.2': 'active', 'dldocs': 'active',
                'custom-user-dashboard-backend-arm64': 'active', 'glusterfs': 'active', 'hdfs': 'active',
                'custom-user-dashboard-backend': 'active', 'nvidia-device-plugin-daemonset': 'active',
                'custom-user-dashboard-frontend-arm64': 'active', 'cloud-fluentd-es-config-v0.1.0': 'active',
                'huawei': 'active', 'fluent-bit': 'active', 'datanode': 'active', 'grafana-configuration': 'active',
                'a910-device-plugin': 'active', 'prometheus-alert': 'active', 'archType': 'arm64',
                'kubernetes.io/hostname': 'atlas01', 'worker': 'active', 'fluent-bit-config': 'active',
                'nginx': 'active', 'alert-templates': 'active', 'kubernetes.io/arch': 'arm64', 'npu': 'active',
                'job-exporter': 'active', 'custom-user-dashboard-frontend': 'active',
                'blobfuse-flexvol-installer': 'active', 'dotnet-server': 'active', 'FragmentGPUJob': 'active',
                'freeflowrouter': 'active', 'default': 'active', 'kubernetes.io/os': 'linux', 'dlws-scripts': 'active',
                'google-cadvisor': 'active', 'dashboard': 'active', 'openresty': 'active', 'node-exporter': 'active',
                'gpuType': 'huawei_npu_arm64'},
     'gpu_allocatable': {'huawei_npu_arm64': 8}, 'InternalIP': '10.31.3.247',
     'scheduled_service': ['webui2', 'cloud-fluentd-es-v2.0.2', 'dldocs', 'custom-user-dashboard-backend-arm64',
                           'glusterfs', 'hdfs', 'custom-user-dashboard-backend', 'nvidia-device-plugin-daemonset',
                           'custom-user-dashboard-frontend-arm64', 'cloud-fluentd-es-config-v0.1.0', 'huawei',
                           'fluent-bit', 'datanode', 'grafana-configuration', 'a910-device-plugin', 'prometheus-alert',
                           'worker', 'fluent-bit-config', 'nginx', 'alert-templates', 'npu', 'job-exporter',
                           'custom-user-dashboard-frontend', 'blobfuse-flexvol-installer', 'dotnet-server',
                           'FragmentGPUJob', 'freeflowrouter', 'dlws-scripts', 'google-cadvisor', 'dashboard',
                           'openresty', 'node-exporter', 'huawei_npu_arm64'], 'gpu_preemptable_used': {}, 'pods': [],
     'gpuType': 'huawei_npu_arm64', 'gpu_used': {}}
